# version: "3.9"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BRICKSET_API_KEY=${BRICKSET_API_KEY}
      - REBRICKABLE_API_KEY=${REBRICKABLE_API_KEY}
      - BRICKOWL_API_KEY=${BRICKOWL_API_KEY}
    volumes:
      - ./app:/app